### ISSUE TITLE
안녕

### ISSUE THREAD

**Issue by replaykim** [JNU-tong/JNU-tongManagementPage#1]
@Songseunghyo1 안녕 구경하다 간단한 팁 줌 
지금 레파지토리에 라이브러리 jar 파일이나 컴파일된 class들이 올라와 있는뎅 이건 사실 없어도 되니 .gitignore에 추가해서 지워 주면 깔끔할듯.
gitignore 파일은 프로젝트 생성하면 만들어주기도 하지만 그걸론 모자람 
https://www.gitignore.io/ 
보통 여기서 자기가 사용하는 환경 넣어서 만들어주는거 사용함 java intellij 정도 추가해서 만들면 될 듯?

++
master에 commit push 바로하지말고
작업전 branch 생성 -> 작업 branch에서 커밋 푸시 -> 이슈 해결 -> master 브랜치로  pull request -> 머지 
이런식으로 진행해봐

**Comment by Songseunghyo1** [comment]
앗 알겠습니당 !!
피드백 감사해용!!
